/**
 * Asserts the generated sitemap against test/fixtures/routes.ts.
 *
 *   npm run seo:assert-sitemap
 *
 * Reads the committed artefacts in public/, because those are what is actually served
 * at https://www.infinus.co/sitemap.xml. They are regenerated by `next-sitemap` in the
 * `postbuild` script, so if they drift from the fixture the cause is either a route
 * change or a next-sitemap.config.js change.
 *
 * This script never writes to public/ and never modifies next-sitemap.config.js. If
 * the current sitemap violates the expected state, it reports and exits non-zero.
 */
import fs from 'node:fs'
import path from 'node:path'
import { EXPECTED_COUNTS, PRODUCTION_ORIGIN, ROUTES, sitemapRoutes } from '../../test/fixtures/routes'
import { Report, main, resolvePaths } from './lib/build-output'

const SITEMAP_INDEX = 'public/sitemap.xml'
const SITEMAP_URLSET = 'public/sitemap-0.xml'

function readLocs(file: string): string[] {
  const xml = fs.readFileSync(file, 'utf8')
  return Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g)).map((m) => m[1].trim())
}

main(() => {
  const { projectRoot } = resolvePaths()
  const indexFile = path.join(projectRoot, SITEMAP_INDEX)
  const urlsetFile = path.join(projectRoot, SITEMAP_URLSET)

  const report = new Report('Sitemap assertions')

  for (const file of [indexFile, urlsetFile]) {
    if (!fs.existsSync(file)) {
      report.check(false, `${path.relative(projectRoot, file)} does not exist`)
      return report.finish()
    }
  }

  // ── sitemap index points at the urlset, on the production origin ───────────────
  const indexLocs = readLocs(indexFile)
  report.check(indexLocs.length === 1, `${SITEMAP_INDEX} should reference exactly 1 sitemap, found ${indexLocs.length}`)
  report.check(
    indexLocs[0] === `${PRODUCTION_ORIGIN}/sitemap-0.xml`,
    `${SITEMAP_INDEX} references ${indexLocs[0]}, expected ${PRODUCTION_ORIGIN}/sitemap-0.xml`
  )

  // ── urlset contents ───────────────────────────────────────────────────────────
  const locs = readLocs(urlsetFile)
  report.note(`${SITEMAP_URLSET} contains ${locs.length} URLs`)

  report.check(
    locs.length === EXPECTED_COUNTS.sitemapUrls,
    `expected ${EXPECTED_COUNTS.sitemapUrls} sitemap URLs, found ${locs.length}`
  )

  // Every URL must be absolute on the production origin, https, no localhost.
  for (const loc of locs) {
    report.check(loc.startsWith(`${PRODUCTION_ORIGIN}`), `sitemap URL ${loc} is not on ${PRODUCTION_ORIGIN}`)
    report.check(!/localhost|127\.0\.0\.1|vercel\.app/.test(loc), `sitemap URL ${loc} points at a non-production host`)
    report.check(!loc.includes('#'), `sitemap URL ${loc} contains a fragment`)
  }

  // No duplicates.
  const dupes = locs.filter((l, i) => locs.indexOf(l) !== i)
  report.check(dupes.length === 0, `sitemap contains duplicate URLs: ${Array.from(new Set(dupes)).join(', ')}`)

  // ── membership against the fixture ────────────────────────────────────────────
  // next-sitemap emits the root as ".../infinus.co" with no trailing slash, while the
  // canonical tag uses ".../infinus.co/". Compare on pathname so that difference does
  // not produce a false failure — it is a next-sitemap formatting choice, not an SEO
  // difference (both resolve to the same document).
  const toPath = (url: string): string => {
    const p = url.slice(PRODUCTION_ORIGIN.length)
    return p === '' ? '/' : p
  }
  const sitemapPaths = new Set(locs.map(toPath))

  for (const route of sitemapRoutes()) {
    report.check(
      sitemapPaths.has(route.path),
      `${route.path} is marked inSitemap in the fixture but is missing from the sitemap`
    )
  }

  const expectedPaths = new Set(sitemapRoutes().map((r) => r.path))
  for (const p of Array.from(sitemapPaths)) {
    report.check(expectedPaths.has(p), `sitemap contains ${p}, which the fixture does not mark inSitemap`)
  }

  // ── explicit exclusion rules ──────────────────────────────────────────────────
  for (const route of ROUTES) {
    if (route.inSitemap) continue
    const why =
      route.kind === 'page-noindex'
        ? 'it is noindex'
        : route.kind === 'page-redirected'
          ? 'it is a redirect source'
          : route.kind === 'page-internal'
            ? 'it is an internal/demo route'
            : route.kind === 'page-framework'
              ? 'it is a framework route'
              : 'it is a route handler'
    report.check(!sitemapPaths.has(route.path), `sitemap must not contain ${route.path} — ${why}`)
  }

  return report.finish()
})
